Add ViewModel
Agilefreaks/FreaksCatalog-Android pull request #11
Opened 2021-08-03 13:14 UTC by cipry13

#### Description
### Add ViewModel to store data

#### [Task](https://trello.com/c/4mUxMWSN/136-android-freaks-screen-viewmodel)

2021-08-03 13:15 UTC, cipry13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android: Freaks Screen - ViewModel](https://trello.com/c/4mUxMWSN/136-android-freaks-screen-viewmodel)

2021-08-04 06:23 UTC, AlexandraDamaschin commented
Please rebase this and will make CR after

2021-08-05 05:59 UTC, AlexandraDamaschin requested changes
Some small changes to fix

2021-08-05 05:59 UTC, AlexandraDamaschin commented on features/freaks/build.gradle.kts
> +    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1")
Let's find a way to extract the version number so it will be easier to maintain.

2021-08-05 05:59 UTC, AlexandraDamaschin commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/FreaksFragment.kt
> +        activity?.actionBar?.title = "Test"
Love this test title

2021-08-05 06:42 UTC, cipry13 commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/FreaksFragment.kt
> +        activity?.actionBar?.title = "Test"
Removed

2021-08-05 07:55 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-08-05 12:40 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-08-05 12:40 UTC, merged