Details
Agilefreaks/FreaksCatalog-Android pull request #13
Opened 2021-08-04 10:36 UTC by srobert99

#### Description
Created details screen, the views are scalabe and it works properly on phone/tablet screens.

#### [Task](task_url)
https://trello.com/c/zdOYA1fX/39-android-freaks-screen-details-screen

#### Related PRs

## Steps to Test or Reproduce

## Risks

2021-08-04 10:41 UTC, srobert99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android: Freaks Screen - Details Screen](https://trello.com/c/zdOYA1fX/39-android-freaks-screen-details-screen)

2021-08-04 10:42 UTC, srobert99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android: Freaks Screen - Details Screen](https://trello.com/c/zdOYA1fX/39-android-freaks-screen-details-screen)

2021-08-05 05:54 UTC, AlexandraDamaschin requested changes
Some improvements.

2021-08-05 05:54 UTC, AlexandraDamaschin commented on build.gradle.kts
> +    val kotlin_version by extra("1.5.21")
Why do you add this?

2021-08-05 05:54 UTC, AlexandraDamaschin commented on commons/ui/src/main/AndroidManifest.xml
> +
Why do you want to add this extra empty line?

2021-08-05 05:54 UTC, AlexandraDamaschin commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/FreakDetailsFragment.kt
> +            viewBinding.skillsTV.text =
What is TV?

2021-08-05 05:54 UTC, AlexandraDamaschin commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/FreakDetailsFragment.kt
> +        val mainActivityTB = (activity as AppCompatActivity).supportActionBar
What means TB ?

2021-08-05 05:54 UTC, AlexandraDamaschin commented on features/freaks/src/main/res/drawable/profile_pick_background.xml
> +
Extra empty space

2021-08-05 05:54 UTC, AlexandraDamaschin commented on features/freaks/src/main/res/values/strings.xml
> +    <string name="cevaCheckBox">Ceva</string>
Love this ceva/altceva code

2021-08-05 05:54 UTC, AlexandraDamaschin commented on features/freaks/src/main/res/values/strings.xml
> +    <string name="back_button">back button</string>
Do we really use all these strings?

2021-08-05 13:53 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-08-05 13:54 UTC, merged