Freaks list
Agilefreaks/FreaksCatalog-Android pull request #16
Opened 2021-08-11 09:07 UTC by cipry13

#### Description
Integrate Backend API 

#### [Task - Trello](https://trello.com/c/8YqKWs3B/154-android-freaks-screen-get-and-show-freaks-from-api)

#### Related PRs

## Steps to Test or Reproduce

## Risks

2021-08-11 09:09 UTC, cipry13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android - Freaks Screen - get and show freaks from API](https://trello.com/c/8YqKWs3B/154-android-freaks-screen-get-and-show-freaks-from-api)

2021-08-11 13:14 UTC, deniscoman requested changes
Good job 👍 . Just some minor improvements.

2021-08-11 13:14 UTC, deniscoman commented on README.md
> +implementation("com.apollographql.apollo:apollo-coroutines-support:${PluginsVersions.APOLLO_VERSION}")
We should keep only things that help us in README.md (like how to download schema). Because the library is already implemented this details are not that important. A link to the documentation should be enough.

2021-08-11 13:14 UTC, deniscoman commented on features/freaks/build.gradle.kts
> +    id("com.apollographql.apollo").version("2.5.9")
We have the version number stored in a const val. We should use it here. That way we are sure that we have the same version all over the app

2021-08-11 13:14 UTC, deniscoman commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/FreaksFragment.kt
> +        findNavController().navigate(R.id.freak_details, bundleOf("freakId" to freakId))
We should extract the key "freakId" somewhere in a constant. That way if someone will change the value we will avoid having issues when we want to get the value from this key

2021-08-11 13:14 UTC, deniscoman commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/ItemAdapter.kt
> +       // Picasso.get().load(item.photo).into(holder.imageView)
Hmmm 🤔

2021-08-11 13:14 UTC, deniscoman commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/repository/FreaksRepository.kt
> +        freaks
Why do we need "freaks" variable here?

2021-08-11 13:14 UTC, deniscoman commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/repository/FreaksRepository.kt
> +        return freaks ?: emptyList()
It's good what you've done here, but can you try to do it using extension function?

2021-08-11 14:49 UTC, alexandru-calinoiu requested changes
I am not able to run this locall, there is a file missing

```
ERROR:/home/calin/Projects/FreaksCatolog/FreaksCatalog-Android/app/build/intermediates/packaged_manifests/prodDebug/AndroidManifest.xml:20: AAPT: error: resource xml/network_security_config (aka com.agilefreaks.freaks_catalog.debug:xml/network_security_config) not found.
    ```

2021-08-12 06:07 UTC, AlexandraDamaschin requested changes
It doesn't work on my machine 
![image](https://user-images.githubusercontent.com/29914519/129146373-62531016-185e-4da6-94ec-b59d4ce3ea72.png)

2021-08-17 12:35 UTC, cipry13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add DI for freaks screen](https://trello.com/c/mSGhzm31/173-add-di-for-freaks-screen)

2021-08-18 10:25 UTC, srobert99 reviewed
Looks good to me

2021-08-18 10:41 UTC, deniscoman approved these changes

2021-08-18 10:41 UTC, merged