Projects list
Agilefreaks/FreaksCatalog-Android pull request #28
Opened 2021-08-27 10:30 UTC by srobert99

#### Description
Added projects-list screen (data got from backend)

#### [Task](task_url)
https://trello.com/c/UvLfqW6k/171-implement-projects-screen

2021-08-27 10:32 UTC, srobert99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement projects screen](https://trello.com/c/UvLfqW6k/171-implement-projects-screen)

2021-08-29 14:58 UTC, cipry13 commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">Freaks Robinho</string>
You should remove testing code once you're done testing

2021-08-29 14:58 UTC, cipry13 commented on buildSrc/src/main/kotlin/BuildAndroidConfig.kt
> +    const val APPLICATION_ID = "com.agilefreaks.freaks.catalog.robinho"
You should remove testing code once you're done testing

2021-08-29 15:05 UTC, cipry13 commented
FreakDetailsRepositoryImplTest.kt and ProjectsViewModelTest.kt are not projects list related

2021-08-30 06:59 UTC, deniscoman commented
Base for this PR should be project-screen instead of develop

2021-08-30 07:03 UTC, deniscoman requested changes

2021-08-30 07:03 UTC, deniscoman commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/ProjectAdapter.kt
> +
Remove extra empty line

2021-08-30 07:03 UTC, deniscoman commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/ProjectsFragment.kt
> +        })
We can extract this in a method called something like "setupRecycleView"

2021-08-30 10:27 UTC, cipry13 commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/ProjectsModule.kt
> +
remove extra empty line

2021-08-30 13:23 UTC, cipry13 commented on features/projects/src/main/res/layout/fragment_projects.xml
> +
remove extra empty line

2021-08-30 13:25 UTC, DeeaMatei requested changes

2021-08-30 13:25 UTC, DeeaMatei commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/FreakDetailsDataSource.kt
> +interface   FreakDetailsDataSource {
Remove extra white space

2021-08-30 13:40 UTC, DeeaMatei approved these changes
Looks good :octocat:

2021-08-31 08:16 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-08-31 08:16 UTC, merged