Fix freaks details screen
Agilefreaks/FreaksCatalog-Android pull request #29
Opened 2021-08-30 10:29 UTC by srobert99

#### Description
Fixed QA issues

#### [Task](task_url)
https://trello.com/c/zdOYA1fX/39-android-freaks-screen-details-screen

#### Related PRs

## Steps to Test or Reproduce

## Risks

2021-08-31 06:40 UTC, cipry13 commented on buildSrc/src/main/kotlin/BuildAndroidConfig.kt
> +    const val APPLICATION_ID = "com.agilefreaks.freaks.catalog"
wrong id (freaks_catalog)

2021-09-01 07:26 UTC, AlexandraDamaschin commented
Please rebase this

2021-09-01 09:04 UTC, srobert99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android: Freaks Screen - Details Screen](https://trello.com/c/zdOYA1fX/39-android-freaks-screen-details-screen)

2021-09-01 10:30 UTC, cipry13 commented on features/freaks/src/main/res/layout/fragment_freak_details.xml
> +                app:cardBackgroundColor="?attr/colorPrimary"
revert this change. color shouldn't be the primary blue.

2021-09-01 10:32 UTC, cipry13 commented on features/freaks/src/main/res/layout/fragment_freak_details.xml
> +                        android:paddingBottom="@dimen/level_bot_margin"
bot?

2021-09-01 10:32 UTC, cipry13 commented on features/freaks/src/main/res/values-sw720dp/dimensions720dp.xml
> +    <dimen name="image_rounded_background_stroke_width">6dp</dimen>
typo

2021-09-01 10:32 UTC, cipry13 commented on features/freaks/src/main/res/values-sw720dp/dimensions720dp.xml
> +    <dimen name="image_roundend_background_radius">15dp</dimen>
typo

2021-09-02 10:55 UTC, AlexandraDamaschin requested changes
Some small improvements

2021-09-02 10:55 UTC, AlexandraDamaschin commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/details/FreakDetailsDataSource.kt
> +    suspend fun getFreaks(freakId: String): FreakDetailsQuery.Data?
Does this function really get Freaks?

2021-09-02 10:55 UTC, AlexandraDamaschin commented on features/freaks/src/main/res/layout/fragment_freak_details.xml
>                  android:id="@+id/cardViewStartG"
What is cardViewStartG?

2021-09-02 12:52 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-09-03 12:20 UTC, merged