Project details
Agilefreaks/FreaksCatalog-Android pull request #30
Opened 2021-08-31 11:00 UTC by DeeaMatei

#### Description

#### [Task](task_url)

#### Related PRs

## Steps to Test or Reproduce

## Risks

2021-09-02 13:02 UTC, DeeaMatei commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement projects details screen](https://trello.com/c/B1GUAOXw/172-implement-projects-details-screen)

2021-09-03 11:44 UTC, AlexandraDamaschin requested changes
Some small questions/improvements

2021-09-03 11:44 UTC, AlexandraDamaschin commented on features/projects/build.gradle.kts
> +    testImplementation(project(mapOf("path" to ":features:freaks")))
Why do we need this?

2021-09-03 11:44 UTC, AlexandraDamaschin commented on features/projects/src/main/graphql/com.agilefreaks.freaks_catalog.features.projects/ProjectDetails.graphql
> +query ProjectDetails {
Is this a ProjectDetails only?

2021-09-03 11:44 UTC, AlexandraDamaschin commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/ProjectsApolloClient.kt
> +package com.agilefreaks.freaks_catalog.features.projects
From what I remember this is added in the project, why do we need to create another apolloclient?

2021-09-03 11:44 UTC, AlexandraDamaschin commented on features/projects/src/test/kotlin/com/agilefreaks/freaks_catalog/features/projects/CoroutineRule.kt
> +package com.agilefreaks.freaks_catalog.features.projects
This seems to be copy/paste code? I have a deja vu I've seen this code already in our app

2021-09-03 11:44 UTC, AlexandraDamaschin commented on features/projects/src/test/kotlin/com/agilefreaks/freaks_catalog/features/projects/ProjectDetailsViewModelTest.kt
> +    fun `loadProject will populate project with values from repository`() = runBlockingTest {
Why are we testing this?

2021-09-06 12:34 UTC, cipry13 commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/Freak.kt
> +)
why do you need this?

2021-09-06 12:43 UTC, cipry13 commented
Project description is missing

2021-09-06 12:44 UTC, cipry13 commented
Photo doesn't have rounded corners and borders

2021-09-06 12:47 UTC, cipry13 commented on features/projects/src/main/res/values/strings.xml
> +    <string name="description">Description: %1$s</string>
"Description:" should not appear on screen

2021-09-06 12:49 UTC, cipry13 commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/details/ProjectDetailsDataSource.kt
> +    override suspend fun getProjectDetails(id: String): ProjectDetailsQuery.Data? =
whose id is this?

2021-09-06 12:53 UTC, cipry13 commented on features/projects/src/main/res/values/strings.xml
> +    <string name="skills">Skills: %1$s</string>
Skill should be renamed to Technologies

2021-09-07 07:54 UTC, srobert99 approved these changes

2021-09-07 08:18 UTC, deniscoman requested changes

2021-09-07 08:18 UTC, deniscoman commented on features/freaks/src/main/kotlin/com/agilefreaks/freaks_catalog/features/freaks/details/DetailsFragmentModule.kt
> +val projectDetailsFragmentModule = module {
Something doesn't feel right here 🤔

2021-09-07 08:18 UTC, deniscoman commented on features/freaks/src/test/kotlin/com/agilefreaks/freaks_catalog/features/freaks/DetailsViewModelTest.kt
It feels like that on rebase you keep the wrong version here :(

2021-09-07 08:18 UTC, deniscoman commented on features/projects/src/main/kotlin/com/agilefreaks/freaks_catalog/features/projects/details/ProjectDetailsFragmentModule.kt
> +val detailsFragmentModule = module {
It's not only here the problem, but this variable and this file name should'n contain fragment in it. It doesn't have anything to do with fragments

2021-09-07 12:57 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-09-07 12:59 UTC, merged