Freaks list
Agilefreaks/FreaksCatalog-Android pull request #5
Opened 2021-07-22 08:53 UTC by cipry13

#### Description

Setup UI and freaks list in the Freaks Screen

#### [Task](https://trello.com/c/7dXztOPH/37-android-freaks-screen-setup-ui-and-freaks-list)

#### Related PRs

## Steps to Test or Reproduce

## Risks

2021-07-22 11:06 UTC, DeeaMatei requested changes
:gem: Looking good, just a few changes needed

2021-07-22 11:06 UTC, DeeaMatei commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/Freak.kt
> +    }
This should display the elements from the lists Skills and Projects, not the whole list like "[iOS, Android]"

2021-07-22 11:06 UTC, DeeaMatei commented on features/freaks/src/main/kotlin/com/agilefreaks.freaks_catalog.features.freaks/ItemAdapter.kt
> +        Log.d("Testing", "$position $item");
Remove this kind of testing

2021-07-22 12:57 UTC, DeeaMatei approved these changes
:rice_ball: Nice

2021-07-23 08:26 UTC, srobert99 approved these changes
very good

2021-07-23 08:26 UTC, srobert99 commented on features/freaks/src/main/res/layout/list_item.xml
> +    app:cardCornerRadius="8dp"
Hard coded values

2021-07-23 08:29 UTC, merged

2021-07-26 06:26 UTC, cipry13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android: Freaks Screen - Setup UI and freaks list](https://trello.com/c/7dXztOPH/37-android-freaks-screen-setup-ui-and-freaks-list)